import App from "../components/App";
import Supplier from "../components/Supplier";
import Head from "next/head";
import Login from "../components/login";
import { useState, useEffect } from "react";

export default function Home() {
    const [didSubmit, setDidSubmit] = useState(false);
    const [supplyLogin, setSupplyLogin] = useState(false);

    useEffect(() => {
        let value = localStorage.getItem("custId");
        if (value) {
            setDidSubmit(true);
            return;
        }
        value = localStorage.getItem("supply_id");
        if (value) {
            setDidSubmit(true);
            setSupplyLogin(true);
        }
    }, []);

    const handleSupplylLogout = () => {
        setDidSubmit(false);
        setSupplyLogin(false);
        localStorage.removeItem("supply_id");
    };

    const handleLogout = () => {
        setDidSubmit(false);
        localStorage.removeItem("custId");
    };

    const handleSubmitSupplier = async (userData) => {
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/supplier`, {
            method: "POST",
            // mode: "no-cors",
            body: JSON.stringify(userData),
            headers: {
                "Content-Type": "application/json",
            },
        });
        let supply_id = await res.json();
        localStorage.setItem("supply_id", supply_id);
        setDidSubmit(true);
        setSupplyLogin(true);
    };

    const handleSubmitCustomer = async (userData) => {
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/customer`, {
            method: "POST",
            // mode: "no-cors",
            body: JSON.stringify(userData),
            headers: {
                "Content-Type": "application/json",
            },
        });
        let cust_id = await res.json();
        localStorage.setItem("custId", cust_id);
        setDidSubmit(true);
    };
    return (
        <div>
            <Head>
                <title>Food Ordering App</title>
                <meta name="description" content="Generated by Lokesh" />
            </Head>
            {didSubmit ? (
                supplyLogin ? (
                    <Supplier logout={handleSupplylLogout} />
                ) : (
                    <App logout={handleLogout} />
                )
            ) : (
                <Login
                    onSubmit={handleSubmitCustomer}
                    onSupply={handleSubmitSupplier}
                />
            )}
        </div>
    );
}
